version: "3"
services:
  tycho_api:
    image: helxplatform/tycho:1.0.22
    volumes:
      - "/tycho"
    entrypoint: /usr/local/bin/gunicorn --workers=2 --bind=0.0.0.0:8099 --name=tycho --timeout=600 tycho.api:app 
    ports:
      - "8099"
