version: "3.6"
services:
  imagej:
    # Uncomment next/remove following line when built in helxplatform
    # image: helxplatform/renci-guacamole-vnc:test
    image: heliumdatastage/renci-guacamole-vnc:test
    container_name: imagej
    entrypoint: /init
    ports:
      - 8080:8080
    volumes:
      - pvc://cloud-top/project:/work/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2000M
        reservations:
          cpus: '0.50'
          memory: 2000M
