apiVersion: v1
kind: Service
metadata:
  labels:
    service: tycho-api
  name: tycho-api
spec:
  type: LoadBalancer
  selector:
    app: tycho-api
  ports:
  - name: http
    port: 8099
    protocol: TCP
    targetPort: 8099
