name: Build-Project
run-name: Build-Project
on: 
  pull_request:
    branches: [ master, develop, main ]
    types: [ opened ]
jobs:
  build-packages:
    uses: helxplatform/helx-github-actions/.github/workflows/build-project-tycho.yml@main
    secrets: inherit