name: Build-Project
run-name: Build-Project
on:
  # Any push with exception to the below listed
  # as they will be built in pypi-upload task. 
  push:
    branches-ignore:
    - master
    - develop
    - main
    tags-ignore:
    - v1.*
    - v2.*
    - v3.*
  # We still test to ensure the build is successful
  # for a 'potential PR'. 
  pull_request:
    branches: [ master, develop, main ]
jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # using the latest minor release of python here.
          # ref: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
          python-version: '3.x'
      - name: Install Package Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
      - name: Build Package
        run: python -m build